---
- name: Create the bearer token secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: bearertoken
        namespace: "{{ prometheus_namespace }}"
      data:
        secret: "{{ token_result.json.token | b64encode }}"
      type: Opaque
