apiVersion: integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: prometheus-operator
spec:
  ingress:
    enabled: true
  config:
    auth:
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
    log:
      level: warn
      mode: console
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
