---
- name: Monitoring Automation Controller with Prometheus + Grafana
  hosts: localhost
  collections:
    - kubernetes.core
    - community.general
    - ansible.utils
  roles:
    - aap-prometheus-grafana-role
